version: '3.7'
services:
  db:
    container_name: carsdb_maria
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: carsdb
      MYSQL_DATABASE: carsdb
      MYSQL_USER: superdjango
      MYSQL_PASSWORD: carsdb
    volumes:
      - mydatavolume:/var/lib/mariadb
volumes:
  mydatavolume:

